spring:
  jackson:
    date-format:   'yyyy-MM-dd HH:mm:ss'
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**

  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /meiteVirtualHosts

logging:
  level:
    com.chuansen: debug
